version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - app-logs:/app/logs

volumes:
  app-logs: